name: Build packages
on:
  workflow_dispatch:
  push:
   branches: [master]
  
jobs:
  build:
    name: ${{ matrix.sdk }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: 
          - openwrt-21.02
          - openwrt-22.03
          - openwrt-23.05
        arch:
         - arm_cortex-a9_vfpv3-d16
         - arm_cortex-a15_neon-vfpv4
         - aarch64_cortex-a53
         - aarch64_cortex-a72
         - mips_24kc
         - mipsel_24kc
         - x86_64
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: arition_repo
          KEY_BUILD: ${{ secrets.OPENWRT_USIGN_PRIVATE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bin/packages/${{ matrix.arch }}/arition_repo
          destination_dir: ${{ matrix.sdk }}/${{ matrix.arch }}
          enable_jekyll: true
